name: Run tests in @avenc/server

on:
  push:
    branches:
      - '*'
#    paths:
#      - apps/server
#      - libs/server-libs
#      - package-lock.json
#  pull_request:
#    paths:
#      - apps/server
#      - libs/server-libs
#      - package-lock.json

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefix apps/server

      - name: Run tests
        run: npm test --prefix apps/server
