name: Run tests in @avenc/server

on:
  push:
    paths:
      - apps/server/**
      - libs/**
      - package-lock.json
      - .github/workflows/test-server.yaml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --prefix apps/server
