name: Run tests in @avenc/server

on:
  push:
    branches:
      - main
    paths:
      - apps/server/**
      - libs/**
      - package-lock.json
      - .github/workflows/test-server.yaml
  pull_request:
    branches:
      - main
    paths:
      - apps/server/**
      - libs/**
      - package-lock.json
      - .github/workflows/test-server.yaml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm i --workspace @avenc/server

      - name: Run tests
        run: npm test --workspace @avenc/server
